services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=time_tracking_app
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - t2app

  backend:
    build: "./express-server"
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=mysql://root:password@mysql:3306/time_tracking_app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - t2app

  frontend:
    build: "./react-frontend"
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_BASE_URL=http://backend:8000
    networks:
      - t2app
      
networks:
  t2app:
    driver: bridge
